Updates release & adds Ubuntu 22.04
sensu/monitoring-plugins pull request #31
Opened 2022-05-04 21:18 UTC by asachs01

This PR updates the version of the plugin to use the latest upstream release (2.3.1 vs 2.2.0) and also adds Ubuntu 22.04 support.

2022-05-05 17:37 UTC, asachs01 commented
I've also validated that downloading the latest version and compiling seems to fix issues with `check_ping`

2022-06-17 02:03 UTC, jspaleta commented
Okay this looks mergable.  But this plugin needs some love to transition from travis into github action based CI/CD before we can realistically do a new release.

2022-06-17 05:52 UTC, jspaleta commented
I have to wonder... 
If the existing ubuntu build doesn't work on latest Ubuntu... something else is wrong.
We shouldn't need to rebuild for all possible linux distributions if we are doing the library detection correctly because of the way gcc symboling works.
In general we should eb able to use the oldest supported version of a particular distro family as the asset tarball and reference it in multiple builds using the appropriate filters in the asset resource definition.

2022-06-17 07:18 UTC, jspaleta requested changes

2022-06-17 07:18 UTC, jspaleta commented on Dockerfile.ubuntu2204
> +ARG SENSU_GO_ASSET_NAME="monitoring-plugins-ubuntu2004"
```suggestion
ARG SENSU_GO_ASSET_NAME="monitoring-plugins-ubuntu2204"
```

2022-06-17 07:22 UTC, merged